### PR TITLE
Replace support for collective.indexing with support for Plone 5.1

### PR DESCRIPTION
**Pull request by datakurre**
It seems that we were working for Plone 5.1 support at the same time with @jensens , but I open this just in case that this helps him. (I already had to go on, so I cannot fix conflicts right now.)

Feel free to close this once @jensens' work is complete.

### CODE REVIEW

**Comment by jensens** [comment]
I stuck a bit with my code today, happy to review your branch.

**Comment by datakurre** [comment]
@jensens Ok. Thanks. I managed to rebase. Test should pass, but have not tried this resulting version with our packages yet.

As stated in title, I did not even try to keep compatibility with Plone < 5.1.

**Comment by jensens** [comment]
I had the same idea to make a 5.1 only version. I think its the way to go. 3.x series is branched away and stable/available for older Plones. I did some further cleanup work and test are green. @agitator will check it in a customer project together with ``dexterity.membrane``. If this works I would say, let's merge an release.

**Comment by agitator** [comment]
tested with client project, lgtm

**Pull request merged**
